add RBAC and CONFIG backup + restore options
Altinity/clickhouse-backup pull request #215
Opened 2021-07-04 08:01 UTC by Slach

add --do-backup-configs, --do-backup-rbac to create command
add --do-restore-configs, --do-restore-rbac to restore command

restore `rbac` and restore `configs` require `clickhouse-server` restart, so it's not applicable on containers and turn off by default
close https://github.com/AlexAkulov/clickhouse-backup/issues/208

2021-07-14 08:11 UTC, AlexAkulov requested changes

2021-07-14 08:11 UTC, AlexAkulov commented on cmd/clickhouse-backup/main.go
> +			UsageText:   "clickhouse-backup create [-t, --tables=<db>.<table>] [-s, --schema] [--do-backup-rbac] [--do-backup-configs] <backup_name>",
Мне кажется тут немного ломается логика старых и новых флагов, т.е.
раньше `clickhouse-backup create` бэкапил всё, а если ты хотел что-то отдельно забэкапить, то задавал флаг. Точно так же с restore. А новые флаги они по другому работают и получается какая-то чехарда.
`clickhouse-backup create` не бэкапит rbac, `clickhouse-backup create --schema` это только метадата бэкапится, а `clickhouse-backup create --do-backup-rbac` кажется должен забэкапить только rbac, а он бэкапит всё плюс rbac. 

Думаю, что RBAC можно всегда пробовать бэкапить и восстанавливать. А на случай если нужно забэкапить или восстановить только его то должен быть флаг --rbac по аналогии с --schema

C бэкапом конфигурации конечно всё сложнее потому-что она специфична. 
Может тогда, для неё нужно сделать опцию в конфиге, вроде `CLICKHOUSE_BACKUP_CONFIG` по умолчанию false.
Так же можно сделать флаг --configs или --etc-configs на случай если нужно откатить или забэкапить только конфиги по аналогии со старыми флагами.

2021-07-14 08:11 UTC, AlexAkulov commented on pkg/backup/backup.go
> +		return backupConfigSize, nil
Передавать в функцию параметр о том, что ей нужно просто завершиться это странно. Этот if нужно наружу вынести и не вызывать функцию если он false.

2021-07-14 08:11 UTC, AlexAkulov commented on pkg/backup/restore.go
> -	}
А зачем убрана проверка на случай если имя бэкапа пустое?

2021-07-14 08:11 UTC, AlexAkulov commented on pkg/backup/restore.go
> -	log.Info("done")
Этот done печатается после полного восстановления бэкапа, чтобы понятно было, что он восстановился до конца, а не прервался.

2021-07-14 08:11 UTC, AlexAkulov commented on pkg/clickhouse/clickhouse.go
> +			disks, err = ch.GetDisks()
Полагаю, что тут нужно вызвать ch.GetDefaultPath(), а не искать эту папку по всем дискам.

2021-07-14 08:11 UTC, AlexAkulov commented on test/integration/storage_configuration.sh
> +cat <<EOT > /etc/clickhouse-server/config.d/storage_configuration.xml
А зачем создание storage_configuration.xml было перенесёно в скрипт? Что-то не работало?

2021-07-14 09:06 UTC, Slach commented on cmd/clickhouse-backup/main.go
> +			UsageText:   "clickhouse-backup create [-t, --tables=<db>.<table>] [-s, --schema] [--do-backup-rbac] [--do-backup-configs] <backup_name>",
Согласен с твоими возражениями насчет "нелогичности"

НО, то, что я сделал фичи полностью в ручную подключаемые, и выключенные по умолчанию, это как раз потому, что я хотел оставить совместимость по поведению по умолчанию со старыми версиями clickhouse-backup

А то допустим делал бекап человек без конфигов, правил конфиги через ansible, проапгрейдил `clickhouse-backup`
и переписал себе конфиги "внезапно" (даже если мы H1 напишем шрифтом в changelog что теперь еще  и конфиги восстанавливаются, все равно никто это читать не будет)

Плюс есть пара спорных моментов в самих объектах для бекапа 

Проблема с `--backup-rbac` в том что он банально может не поддерживаться в конкретной версии clickhouse и доступен с `20.4`
и нет нормального способа определить , включен сейчас RBAC или нет,  а также где этот RBAC сейчас на самом деле хранится

то есть даже настройку не посмотреть которая `access_control_path` через SQL и через `clickhouse extract-from-config` тоже не сделать потому что ему нельзя скормить просто `clickhouse extract-from-config -c /etc/clickhouse-server/ -k access_control_path`

проблема с `--backup-config`, в том что его нельзя восстановить в kubernetes окружении где он в большинстве случаев уже смонтирован как read-only file system через ConfigMap

поэтому хочется чтобы фичи были сделаны. но включались только для тех кому они действительно нужны и что эти люди понимают что ни делают

@alex-zaitsev можешь поучавствовать в дискуссии?

2021-07-14 09:14 UTC, Slach commented on pkg/backup/restore.go
> -	}
Она не убрана
Она вынесена в начало функции Restore
https://github.com/AlexAkulov/clickhouse-backup/pull/215/files#diff-59718d24adef263b3b224c44b21735795ec8e96b952e96724a81e59500dff19bR39

Потому что я нашел общий повторяющийся код, который был в двух функциях `RestoreSchema` и `RestoreData`
которые только из Restore вызываются

2021-07-14 09:15 UTC, Slach commented on pkg/backup/restore.go
> -		return fmt.Errorf("select backup for restore")
вот еще одно повторяющееся место которое я вынес за пределы функции

2021-07-14 09:45 UTC, Slach commented on pkg/backup/backup.go
> +		return backupConfigSize, nil
ой, да, что-то перемудрил, пофиксил

2021-07-14 10:02 UTC, Slach commented on test/integration/storage_configuration.sh
> +cat <<EOT > /etc/clickhouse-server/config.d/storage_configuration.xml
Да, не работали тесты на ci/cd
см. https://github.com/Altinity/clickhouse-backup/runs/2979904335?check_suite_focus=true

тут была гонка курицы и яйца
`storage_policy.xml` в котором ссылки на hdd_data1 и hdd_data2 грузился как конфиг `clickhouse` server при попытке обработать `/docker-entrypoint-initdb.d/init.sh` внутри `/entrypoint.sh` и clickhouse контейнер отваливался, потому что hdd_data еще не создан
вообще даже непонятно, как оно до этого работало

2021-07-14 10:07 UTC, Slach commented on pkg/clickhouse/clickhouse.go
> +			disks, err = ch.GetDisks()
Не, тут вообще довольно большая свинья зарыта, если user_policy недоступна, то вообще access_control_path может быть где угодно, ну да, по умолчанию она в `ch.GetDefaultPath() / access`

Возможно надо из папки  /etc/clickhouse-server/ из всех конфигов пытаться доставать эту настройку, если не нашли в GetDefaultPath, может даже проще тупо через поиск без XML парсинга?

Как считаешь?

2021-07-14 10:33 UTC, Slach commented on pkg/backup/restore.go
> -	log.Info("done")
fixed on https://github.com/AlexAkulov/clickhouse-backup/pull/215/commits/dca81b5f090320383102accadf23c54814c50823

2021-07-19 03:01 UTC, Slach commented on pkg/clickhouse/clickhouse.go
> +			disks, err = ch.GetDisks()
Дак это, как считаешь? как лучше сделать то ?

2021-07-20 12:35 UTC, AlexAkulov commented on pkg/clickhouse/clickhouse.go
> +			disks, err = ch.GetDisks()
Я думаю надо просто смотреть если есть `ch.GetDefaultPath() / access`, просто скопировать их и всё. Если ты сам себе злой буратино и как-то хитро задал access_control_path то иди и перенастрой на access если хочешь их бэкапить.

2021-07-27 06:58 UTC, AlexAkulov commented on pkg/backup/restore.go
> +	if err != nil {
Почему `if err == nil` превратилось в `if err != nil`?

2021-07-27 07:07 UTC, AlexAkulov commented on pkg/server/server.go
> +	return err
Очень странная обработка ошибки. 
Тут надо либо ошибку в канал передвать и где-то её ловить и обрабатывать, либо ждать когда горутины завершатся, либо вернуть всё как было и настроить линтенер у себя.

2021-07-27 07:09 UTC, AlexAkulov commented on pkg/server/server.go
> +			api.status.stop(err)
Тоже вопрос, defer тут осознанно появился или потому-что просто линтер предложил?

2021-07-27 07:11 UTC, AlexAkulov commented on test/integration/integration_test.go
> -	}
Вот эти изменения предлагаю вынести в отдельный пулл-реквест

2021-07-27 07:18 UTC, AlexAkulov commented on test/integration/storage_configuration.sh
> +cat <<EOT > /etc/clickhouse-server/config.d/storage_configuration.xml
Не должно быть никакой гонки, там в entrypoint у кликхауса, он сначала выполняет скрипты в /docker-entrypoint-initdb.d/, а потом запускает КликХаус

2021-07-27 14:27 UTC, Slach commented on pkg/backup/restore.go
> +	if err != nil {
Бес попутал =) опечатка, хотелось отрефакторить этот кусок и откатил обратно

2021-07-27 14:28 UTC, Slach commented on pkg/server/server.go
> +			api.status.stop(err)
defer убрал потому что linter предложил, типа defer внутри for, может привести к утечкам ресурсов

2021-07-27 14:43 UTC, Slach commented on pkg/server/server.go
> +	return err
да, спасибо большое, глупый код написал, надо действительно либо ошибку нормально обработать либо горутину дождаться, извини, откатил

2021-07-27 14:44 UTC, Slach commented on pkg/server/server.go
> +	return err
fixed on https://github.com/AlexAkulov/clickhouse-backup/pull/215/commits/596ac930d170c3c5c0944e6698e7f00912c5321f

2021-07-27 14:50 UTC, Slach commented on cmd/clickhouse-backup/main.go
> +			UsageText:   "clickhouse-backup create [-t, --tables=<db>.<table>] [-s, --schema] [--do-backup-rbac] [--do-backup-configs] <backup_name>",
@AlexAkulov переделал
теперь по умолчанию --rbac --configs работают также как --schema --data
при восстановлении если есть конфиги, rbac будет рестарт сервера
но можно при восстановлении указать --skip-rbac --skip-configs и это восстанавливаться не будет

2021-07-28 07:57 UTC, AlexAkulov commented on pkg/server/server.go
> +			api.status.stop(err)
Сорян, показалось ты его добавил. Тогда всё ок, да.

2021-07-28 20:55 UTC, merged