Add TestFlows tests to GH workflow
Altinity/clickhouse-backup pull request #5
Opened 2022-01-17 18:36 UTC by zvonand

2022-01-19 12:08 UTC, Slach requested changes

2022-01-19 12:08 UTC, Slach commented on test/testflows/clickhouse_backup/requirements/requirements.py
> +# These requirements were auto generated
Where stored source Markdown file for `requirements.py`?
Please add it to PR

2022-01-19 12:08 UTC, Slach commented on test/testflows/clickhouse_backup/tests/snapshots/cli.py.cli.snapshot
> +default_config = r"""['general:', 'remote_storage:', 'none', 'max_file_size:', '107374182400', 'disable_progress_bar:', 'true', 'backups_to_keep_local:', '0', 'backups_to_keep_remote:', '0', 'log_lev
is this file should be present in PR?
what exactly stored in this file?

2022-01-19 12:12 UTC, Slach requested changes
I don't see where is `test/testflows/REQUIREMENTS.md`
and `test/testflows/requirements.txt`
and instruction how to install python + testflows  and run test locally

2022-01-19 14:29 UTC, zvonand commented on test/testflows/clickhouse_backup/configs/clickhouse1/users.xml
> +<?xml version="1.0"?>
What's wrong with users.xml? 
We have this in all QA projects

2022-01-19 14:31 UTC, zvonand commented on test/testflows/clickhouse_backup/tests/snapshots/cli.py.cli.snapshot
> +default_config = r"""['general:', 'remote_storage:', 'none', 'max_file_size:', '107374182400', 'disable_progress_bar:', 'true', 'backups_to_keep_local:', '0', 'backups_to_keep_remote:', '0', 'log_lev
These are snapshots for tests - e.g. we compare results of command like default-config to see if something is changed in new versions

2022-01-19 15:14 UTC, Slach commented on test/testflows/clickhouse_backup/configs/clickhouse1/users.xml
> +<?xml version="1.0"?>
You override default `/etc/clickhouse-server/user.xml` instead of extends it
This config come inside clickhouse with deb package
You can break clickhouse behavior in future if `clickhouse-server` will re-define some behavior during default config

2022-01-30 17:13 UTC, zvonand commented on test/testflows/clickhouse_backup/configs/clickhouse1/users.xml
> +<?xml version="1.0"?>
The image we use is clickhouse-integration-test, not just clickhouse. There is no default config files - they must all be explicitely specified.

2022-01-30 18:10 UTC, zvonand commented on test/testflows/clickhouse_backup/configs/clickhouse1/config.xml
> +<?xml version="1.0"?>
The image we use is clickhouse-integration-test, not just clickhouse. There is no default config files - they must all be explicitely specified.

2022-02-03 17:25 UTC, merged

2022-02-03 17:25 UTC, Slach commented
ok. let's merge it and try to make all green