server: Add callbacks query param
Altinity/clickhouse-backup pull request #636
Opened 2023-04-18 00:27 UTC by mskwon

Add callbacks query param, which can be used by clients to the server for notifications on completion of an asynchronous operation.

Callback support is added to the following endpoints:

    /backup/create
    /backup/upload/{name}
    /backup/download/{name}
    /backup/restore/{name}

The callback parameter can be passed to the target endpoint with the addition of

?callback={URI Encoded Callback URL}

Callback payloads are POSTed with the JSON serialized struct CallbackResponse, which is exported for use by clients. Multiple callback URLs can be specified; all URLs will be hit regardless of failures in any single endpoint.

Resolves AlexAkulov/clickhouse-backup#635

2023-04-18 16:25 UTC, Slach commented
looks amazing, thanks for contribution, need more time to review

2023-04-19 08:21 UTC, Slach requested changes
code looks clear
could you add callback parameter description to ReadMe.md API sections?

2023-04-19 08:47 UTC, Slach approved these changes

2023-04-19 08:47 UTC, Slach commented
i will add it later

2023-04-19 08:47 UTC, merged

2023-04-19 16:34 UTC, mskwon commented
Thank you!