respect max_parts_count
Altinity/clickhouse-backup pull request #740
Opened 2023-09-05 12:49 UTC by rodrigargar

Fix https://github.com/Altinity/clickhouse-backup/issues/739

2023-09-05 13:18 UTC, Slach requested changes

2023-09-05 13:18 UTC, Slach commented on pkg/storage/general.go
> +				bufferSize++
this changes do nothing

2023-09-05 13:18 UTC, Slach commented on pkg/storage/s3.go
> +		partSize = 5 * 1024 * 1024
good catch

2023-09-05 13:18 UTC, Slach commented on pkg/storage/s3.go
> +		partSize++
try to explain what exactly this change should fix?

2023-09-05 14:42 UTC, rodrigargar commented on pkg/storage/s3.go
> +		partSize++
If the size of the upload is not divisible by MaxPartsCount, you will need MaxPartsCount + 1 parts to complete the upload with the calculated part size because the integer division truncates the result.

A couple of lines later:
```
// Calculate the number of parts (equals to MaxPartsCount + 1 if srcSize not divisible by MaxPartsCount)
numParts := (srcSize + partSize - 1) / partSize
```

 Adding 1 to the partSize ensures that the MaxPartsCount will not be exceeded.

2023-09-07 12:39 UTC, Slach approved these changes

2023-09-07 12:39 UTC, Slach commented
could you merge latest master to your branch?

2023-09-07 16:31 UTC, merged