Fix backup hanging.
Altinity/clickhouse-backup pull request #753
Opened 2023-09-28 07:12 UTC by minguyen-jumptrading

Backup upload to GCS hangs indefinitely

2023-09-28 07:18 UTC, Slach requested changes

2023-09-28 07:18 UTC, Slach commented on pkg/storage/gcs.go
> +		// gcs.clientPool.InvalidateObject(ctx, pClientObj)
could you remove commented code?

2023-09-28 07:22 UTC, minguyen-jumptrading commented on pkg/storage/gcs.go
> +		// gcs.clientPool.InvalidateObject(ctx, pClientObj)
sure

2023-09-28 07:24 UTC, minguyen-jumptrading commented on pkg/storage/gcs.go
> +		// gcs.clientPool.InvalidateObject(ctx, pClientObj)
done

2023-10-03 10:59 UTC, Slach approved these changes

2023-10-03 10:59 UTC, merged